name: CI/CD Pipeline

on:
  push:
    branches:
      - master # if pushed to master launch pipeline

# pipeline job definition
jobs:
  build:
    runs-on: ubuntu-latest # choosing ubuntu vm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # cloning repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # installing Python 3.9

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt  # installing dependencies from requirements.txt

      - name: Run code
        run: |
          python backend/app.py # test that code runs

      - name: Deploy to Staging
        env:
          API_KEY: ${{ secrets.API_KEY }} # Github Secrets example
        run: |
          echo "Deploying to staging with key $API_KEY..."  # This will show *** instead of our secret
